### PR TITLE
Refactor of AWS data interface

### PR DESCRIPTION
**Pull request by jmanero-r7**
- Refactor into a separate CLI
- Expose 'lookup' method to the Buildfile DSL

### CODE REVIEW

**Comment by jmanero-r7** [comment]
@simonirwin-r7, update usage looks like

``` bash
jmanero@computer: ~/workspace/builderator $ bundle exec build-data image -f windows-server2012-r2
ami-e171098b, ami-1df0ac78, ami-e3fcb686
jmanero@bos-mbp-2688: ~/workspace/builderator $ be build-data image -f windows-server2012-r2-core -l
ami-e07c048a
```

**Comment by athompson-r7** [comment]
What does the usage look like if you aren't using a pre-defined filter?

**Comment by jmanero-r7** [comment]
Pass it pairs of key value filters like `name AMI_NAME virtualization-type hvm ...`

**Comment by athompson-r7** [comment]
LGTM

**Pull request merged**
