### PR TITLE
Update berkshelf dependency

### PR DESCRIPTION
**Pull request by dgreene-r7**
This PR updates the Berkshelf dependency to 5.6.x. This update allows us to deprecate the Berkshelf patch that was being used.

It also adds a `-v/--version` task to print the current Builderator version.

### CODE REVIEW

**Comment by athompson-r7** [comment]
What are the validation steps we need to do to make sure we are still resolving/pushing cookbooks correctly?

**Comment by rdickey-r7** [comment]
I remember there being an issue with berkshelf 5.x for something, but I don't recall exactly what it was, just that going back to 4.x fixed the glitch.  @cdoughty-r7 mentioned it was a ruby not being supported; is that the case and is it fixed or do we care?

**Comment by dgreene-r7** [comment]
Based on the [Changelog](https://github.com/berkshelf/berkshelf/blob/master/CHANGELOG.md) it seems like the only big thing is that they deprecated the use of Ruby 2.1.

**Comment by dgreene-r7** [comment]
Moving to 6.x requires an update to Ruby `> 2.3.1`.

**Pull request merged**
