### PR TITLE
📝 Document the new default for autoversion.create_tags

### LINKED ISSUE #56: autoversion.create_tags docs inconsistent with defaults
Documentation and code defaults for `autoversion.create_tags` are inconsistent.  I'm not sure which is right.

https://github.com/rapid7/builderator/blob/master/lib/builderator/config/defaults.rb#L16
and 
https://github.com/rapid7/builderator/blob/master/docs/versioning.md#configuration

### PR DESCRIPTION
**Pull request by erran**
Fixes #56.

See also fd072540fc where this default was updated.

### CODE REVIEW

**Comment by erran** [comment]
ping @athompson-r7 and @jmanero-r7

**Comment by jmanero-r7** [comment]
Sorry @erran. Looks good 👍

**Comment by jmanero-r7** [comment]
Can you rebase this back up to master?

**Comment by erran-r7** [comment]
@jmanero-r7 sure!

**Comment by erran-r7** [comment]
> Can you rebase this back up to master?

@jmanero-r7 Pushed with 5a2ad26.

**Pull request merged**
