### PR TITLE
Add integration interfaces

### PR DESCRIPTION
**Pull request by jmanero-r7**
Adds configuration generators for Berkshelf, Packer, and Vagrant

### CODE REVIEW

**Comment by fmitchell-r7** [comment]
Do I have to use all the things in my Buildfile, or can I roll my own Vagrantfile but have builderator generate my Packer JSON file?

**Comment by jmanero-r7** [comment]
Yep. It generates all of the integration configs in .builderator

**Comment by jmanero-r7** [comment]
@fmitchell-r7 I've added a note to README. Problem is that provisioners aren't scoped to builders, so we can't just use the `ssh_username` for it :disappointed:

**Comment by jmanero-r7** [comment]
Erm... wait, https://github.com/rapid7/builderator/pull/11#issuecomment-161784086 is kind of ambiguous...

You may keep a Vagrantfile in the repo, as well as a Berksfile. The interfaces write their generated files into .builderator, and execute vagrant and berks therein

**Pull request merged**
